version: "3.1"
services:
    www:
        build:
            dockerfile: Dockerfile-php
        ports: 
            - "8080:80"
            - "8000:443"
        volumes:
            - ./www:/var/www/html/
        depends_on:
                - mysql

    mysql:
        image: mysql
        command:
            --authentication_policy=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
        environment:
            TZ: Asia/Hong_Kong
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: COMP3335_Project
            MYSQL_USER: user
            MYSQL_PASSWORD: test
        ports: 
            - "33306:3306"
        volumes:
            - ./mysql/dump:/docker-entrypoint-initdb.d
            - ./mysql/conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql


    phpmyadmin:
        build:
            dockerfile: Dockerfile-admin
        ports:
            - "8081:80"
            - "8001:443"
        environment:
            PMA_HOST: '127.0.0.1'
            PMA_PORT: '33306'
            PMA_USER: 'root'
            PMA_PASSWORD: "test"
        depends_on:
            - mysql

volumes:
    persistent:
