version: "3.1"
services:
    www:
        build:
            dockerfile: Dockerfile-php
        ports: 
            - "8080:80"
            - "8000:443"
        volumes:
            - ./www:/var/www/html/
        depends_on:
                - db

    db:
        image: mysql
        command:
            --authentication_policy=mysql_native_password
            --host_cache_size=0
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
        environment:
            TZ: Asia/Hong_Kong
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
        ports: 
            - "33306:3306"        
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql

    phpmyadmin:
        build:
            dockerfile: Dockerfile-admin
        ports:
            - "8081:80"
            - "8001:443"
        environment:
            PMA_HOST: 'db'
            PMA_PORT: '3306'
            PMA_USER: 'root'
            PMA_PASSWORD: "test"
        depends_on:
            - db
            
volumes:
    persistent:
